name: atinout-armvirt64

on:
  workflow_dispatch:

env:
  REPO_SDK: https://downloads.openwrt.org/releases/21.02.5/targets/armvirt/64/openwrt-sdk-21.02.5-armvirt-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz

jobs:
  build:
    runs-on: ubuntu-20.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download sdk
        run: |
          wget ${REPO_SDK}
          tar xf *.tar.xz
          rm -f *.tar.xz
          mv openwrt-* openwrt
          
      - name: Get atinout source
        run: |
          cd openwrt/package/
          svn co https://github.com/4IceG/luci-app-atinout-mod/tags/1.3.2-20220315/ ./
      
      - name: Updating feeds
        run: |
          cd openwrt/
          ./scripts/feeds update -a
          
      - name: Installing feeds
        run: |
          cd openwrt/
          ./scripts/feeds install -a
      
      - name: Compile the atinout
        run: |
          mkdir -p packed
          cd openwrt/
          make defconfig
          make package/atinout/compile -j${nproc} V=w
          find bin/ -type f -name '*atinout*' -exec mv -t ../packed {} +
         
      - name: Upload Package to Releases
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: 21.02.5-armvirt64
          artifacts: "packed/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
